### ISSUE TITLE
I tried running the sample code and got error

### ISSUE THREAD

**Issue by MrZombie69232** [phayne/heat1d#3]
`# **Standard libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

# Planetary libraries
from heat1d import prettyPlots
import planets
import heat1d

prettyPlots.setStyle()`**

Error:- 

> ttributeError                            Traceback (most recent call last)
> <ipython-input-12-0bd4f23391bf> in <module>
>       6 # Planetary libraries
>       7 from heat1d import prettyPlots
> ----> 8 import planets
>       9 import heat1d
>      10 
> 
> C:\conda\lib\site-packages\planets\__init__.py in <module>
>       7 __version__ = '0.4.5'
>       8 
> ----> 9 from ._planets import *
> 
> C:\conda\lib\site-packages\planets\_planets.py in <module>
>      17 # Dependencies
>      18 import numpy as np
> ---> 19 import spiceypy as spice
>      20 from astropy import units as u
>      21 from astropy.constants import G, au, sigma_sb
> 
> C:\conda\lib\site-packages\spiceypy\__init__.py in <module>
>      23 """
>      24 
> ---> 25 from .spiceypy import *
>      26 from .utils import support_types
>      27 
> 
> C:\conda\lib\site-packages\spiceypy\spiceypy.py in <module>
>      26 from .utils import support_types as stypes
>      27 from .utils.support_types import Cell_Char, Cell_Bool, Cell_Double, Cell_Int, Cell_Time
> ---> 28 from .utils.libspicehelper import libspice
>      29 from . import config
>      30 from .utils.callbacks import SpiceUDFUNS, SpiceUDFUNB
> 
> C:\conda\lib\site-packages\spiceypy\utils\libspicehelper.py in <module>
>      97 libspice.ckcov_c.argtypes = [c_char_p, c_int, c_int, c_char_p, c_double, c_char_p, s_cell_p]
>      98 libspice.ckobj_c.argtypes = [c_char_p, s_cell_p]
> ---> 99 libspice.ckfrot_.argtypes = [c_int_p, c_double_p, (c_double * 3) * 3, c_int_p, c_int_p]
>     100 libspice.ckgp_c.argtypes = [c_int, c_double, c_double, c_char_p, ((c_double * 3) * 3), c_double_p,
>     101                             c_int_p]
> 
> C:\conda\lib\ctypes\__init__.py in __getattr__(self, name)
>     375         if name.startswith('__') and name.endswith('__'):
>     376             raise AttributeError(name)
> --> 377         func = self.__getitem__(name)
>     378         setattr(self, name, func)
>     379         return func
> 
> C:\conda\lib\ctypes\__init__.py in __getitem__(self, name_or_ordinal)
>     380 
>     381     def __getitem__(self, name_or_ordinal):
> --> 382         func = self._FuncPtr((name_or_ordinal, self))
>     383         if not isinstance(name_or_ordinal, int):
>     384             func.__name__ = name_or_ordinal
> 
> AttributeError: function 'ckfrot_' not found
> 

Above is the error I am getting

**Comment by michaelaye** [comment]
can you try `pip install -U planets` and then try again?

**Comment by MrZombie69232** [comment]
Still getting the same error . 
Also I have been trying to contact you on Diviner . I need your help . Can you please provide me your email via that I can contact ?

**Comment by michaelaye** [comment]
Which operating system is this on? B/c this looks like a rare spiceypy bug.

You can find out if this is a spiceypy bug by trying this:

```python
import spiceypy as spice
```
If you get an error at that point, you should report that problem here: https://github.com/AndrewAnnex/SpiceyPy with all details regarding your installation: OS, Python distribution, etc.

**Comment by MrZombie69232** [comment]
I got the error while trying to import spiceypy as spice .
even Import planets not working

**Comment by michaelaye** [comment]
Planets depends on spiceypy, so the word “even” doesn’t make sense here. You got to first fix the error with spiceypy. Then planets should work fine. Reopen this issue if it then still doesn’t work.
